name: "ワークフローの情報"
on: workflow_dispatch

jobs:
  info:
    name: Information
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: whoami
      - run: pwd
      - run: ls -AF1
      - run: bash --version
      - run: node -v
      - run: npm -v
      - run: git --version